### ISSUE TITLE
Many package suggestions: 

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/Agriculture#38]
[Source](https://github.com/cran-task-views/ctv/issues/27#issuecomment-1231331113)

Not sure i could give my two cents, but anyway here are.
I would suggest some packages for your consideration:
*https://cran.r-project.org/package=FielDHub /
https://github.com/DidierMurilloF/FielDHub* A shiny design of
experiments (DOE) app that aids in the creation of traditional,
un-replicated, augmented and partially-replicated designs applied to
agriculture, plant breeding, forestry, animal and biological sciences.
*Category: Experimental design

***Not on CRAN / *https://github.com/OpenDroneMap/FIELDimageR *
FIELDimageR: A Tool to Analyze Images From Agricultural Field Trials and
Lab in R. Manipulation of Multispectral images, plant part count.
*Category: High throughput phenotyping (HTP)

***https://cran.r-project.org/package=photosynthesis /
*https://github.com/cdmuir/photosynthesis* package with modeling tools
for C3 photosynthesis, as well as analytical tools for curve-fitting
plant ecophysiology responses. *Category: Crop growth models & crop
modelling

***https://cran.r-project.org/package=tealeaves /
*https://github.com/cdmuir/tealeaves*    package to model leaf
temperature using leaf energy balance, companion of photosynthesis
*Category: Crop growth models & crop modelling

***https://cran.r-project.org/package=plantecophys /
*https://github.com/remkoduursma/plantecophys* package that bundles a
number of tools to analyze and model leaf gas exchange data. *Category:
Crop growth models & crop modelling

***Not on CRAN / *https://github.com/jstinzi/plantecowrap* add to
capabilities to 'plantecophys' include temperature responses of
mesophyll conductance (gm, gmeso), apparent Michaelis-Menten constant
for rubisco carboxylation in air (Km, Kcair),and photorespiratory CO2
compensation point (GammaStar) for fitting A-Ci or A-Cc curves for C3
plants, ability to fit the Arrhenius and modified Arrhenius temperature
response functions for maximum rubisco carboxylation rates (Vcmax) and
maximum electron transport rates (Jmax)
*Category: Crop growth models & crop modelling

***https://cran.r-project.org/package=bigleaf /
*https://bitbucket.org/juergenknauer/bigleaf/src/master/* package for
the calculation of physical (e.g. aerodynamic conductance, surface
temperature) and physiological (e.g. canopy conductance, water-use
efficiency) ecosystem properties from eddy covariance data and
accompanying meteorological measurements *Category: Crop growth models &
crop modelling

***Not on CRAN / *https://github.com/rasenior/ThermStats*         and
**https://cran.us.r-project.org/package=Thermimage /
*https://github.com/gtatters/Thermimage* *First *is R package addresses
current constraints on applying thermography in ecology, by speeding up
and simplifying the extraction of data from (FLIR) thermal images, and
by facilitating the calculation of different metrics of thermal
heterogeneity for any gridded temperature data. *Second *is a collection
of functions for assisting in converting extracted raw data from
infrared thermal images and converting them to estimated temperatures
using standard equations in thermography. Provides an open source proxy
tool for assisting with infrared thermographic analysis. Both require
the external software ExifTool or, easier for R newbie IMHO,
*https://github.com/JoshOBrien/exiftoolr **Category: Crop growth models
& crop modelling

***Not on CRAN / *https://github.com/poppinace/tasselnetv2plus* A Fast
Implementation for High-Throughput Plant Counting from High-Resolution
RGB Imagery. Some functionalities could be similar to FILEDimageR, but
with completely different approach. *Category: High throughput
phenotyping (HTP)
*
**https://cran.r-project.org/package=DataExplorer  /
*https://github.com/boxuancui/DataExplorer* Exploratory Data Analysis
(EDA) *Category: Trial analysis*

*https://cran.r-project.org/package=ggstatsplot    /
*https://github.com/IndrajeetPatil/ggstatsplot
*Not on CRAN / *https://easystats.r-universe.dev/ui#packages
*https://cran.r-project.org/package=rstatix /
*https://github.com/kassambara/rstatix
all 3 above pkgs for simple and intuitive pipe-friendly framework,
coherent with the ‘tidyverse’ design philosophy *Category:  Trial analysis*

Hope it helps
Massimiliano

**Comment by adamhsparks** [comment]
Should we include non-CRAN packages? I'd refrained from this since it is a **CRAN** Task View

**Comment by ScymnusRIP** [comment]
@adamhsparks  i've included non-CRAN packages due to in first post was written "The majority of these packages are on CRAN, but a few can only be found on GitHub and other alternative repositories." so, IMHO, to be on CRAN is not mandatory

**Comment by ScymnusRIP** [comment]
@jpiaskowski
 I forgot one package
*https://cran.r-project.org/package=metan/
*https://github.com/TiagoOlivoto/metan
metan (aka multi-environment trials analysis) provides useful functions for analyzing multi-environment trial data using parametric and non-parametric methods. With lovely cheat sheet [here](https://github.com/TiagoOlivoto/metan/raw/master/metan_cheat_sheet.pdf).
 Category: Trial analysis

**Comment by jpiaskowski** [comment]
Thank you. The CRAN task views do allow github/gitlab/r-forge packages, but they cannot be "core packages".

**Comment by adamhsparks** [comment]
Ah! My misunderstanding then. I’d have listed many of these and more already. 😁

**Comment by jpiaskowski** [comment]
I think [ThermStats](https://github.com/rasenior/ThermStats) and [Thermimage](https://cran.r-project.org/package=Thermimage) probably belong in the [Environmetrics](https://cran.r-project.org/web/views/Environmetrics.html) task view. Anyone - please weigh in on what you think. 

[DataExplorer](https://cran.r-project.org/package=DataExplorer), [ExifTool](https://github.com/JoshOBrien/exiftoolr), [ggstatsplot]https://cran.r-project.org/package=ggstatsplot(), and [rstatix](https://cran.r-project.org/package=rstatix) are too general of packages for this task view. 

Other than that, all the other packages have been added. Thank you for your contributions!
