### ISSUE TITLE
Updated info on MegaLMM

### ISSUE THREAD

**Issue by deruncie** [cran-task-views/Agriculture#41]
MegaLMM is not really a GWAS tool – it’s more for genomic prediction. For GWAS you could instead include GridLMM: https://github.com/deruncie/GridLMM, https://doi.org/10.1371/journal.pgen.1007978 which is a GWAS tool and allows you to include multiple random effects to account for multiple sources of confounders. I think MegaLMM would best be described as a tool for multi-trait and/or multi-environment genomic prediction following our paper here: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02416-w

 

`r github("deruncie/GridLMM")` provides functions to run GWAS in models that require 2+ random effects (e.g. additive and dominance kinship matrices, or kinship and spatial covariance matrices)

 

(within Multiple environments and traits:) `r github("deruncie/MegaLMM")` implements multivariate genomic prediction with very large numbers of traits (up to several thousand) using several Bayesian genomic prediction models.

**Comment by jpiaskowski** [comment]
Thank you! changes made (it may take few days for this to be reflected in the published task view
