### ISSUE TITLE
Package 'CropScapeR' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Agriculture#47]
Package [CropScapeR](https://CRAN.R-project.org/package=CropScapeR) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by adamhsparks** [comment]
Thanks, I've opened an issue to find if there are intentions of reinstating or if I can be of assistance.

**Comment by zeileis** [comment]
Thank you Adam @adamhsparks very much appreciated.

**Comment by adamhsparks** [comment]
Should be reinstated, https://github.com/cbw1243/CropScapeR/issues/4#issuecomment-1401365517

**Comment by adamhsparks** [comment]
This package is back on CRAN now. Thanks for alerting us.
