### ISSUE TITLE
Package 'RGISTools' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Agriculture#48]
Package [RGISTools](https://CRAN.R-project.org/package=RGISTools) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
In case you come GHA let us know. This might be useful for other task views as well.

**Comment by jpiaskowski** [comment]
We have reached out [here](https://github.com/spatialstatisticsupna/RGISTools/issues/15).

**Comment by jpiaskowski** [comment]
package is officially deprecated. replacement version is [rsat](https://github.com/ropensci/rsat)

**Comment by janetw** [comment]
Fixed: https://github.com/cran-task-views/Agriculture/pull/55
