### ISSUE TITLE
Add agriwater

### ISSUE THREAD

**Issue by adamhsparks** [cran-task-views/Agriculture#50]
The GitHub repo doesn't appear to be in sync with CRAN, but it just got an update today, presumably removing {rgdal}, {rgeos}, and {rmaptools} since I only see {terra} in the Imports. 

https://cran.r-project.org/web/packages/agriwater/index.html

I'll send through a PR

**Comment by jpiaskowski** [comment]
this looks awesome, good suggestion!

**Comment by adamhsparks** [comment]
😎 I'll get the PR put together shorly.

**Comment by cesarofs** [comment]
What a wonderful surprise for me to come here to ask you to add my package and find out that you are already doing that =D

**Comment by jpiaskowski** [comment]
[merged](https://github.com/cran-task-views/Agriculture/pull/53).
