### ISSUE TITLE
Package 'isqg' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Agriculture#52]
Package [isqg](https://CRAN.R-project.org/package=isqg) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by jpiaskowski** [comment]
@janetw Can you handle this?

**Comment by janetw** [comment]
@jpiaskowski I have some deadlines for this week on two other projects but will hopefully address these issues next week.

**Comment by jpiaskowski** [comment]
I can't find the package on Github, GitLab,BitBucket, or R-forge so perhaps it is not being actively maintained anymore?

**Comment by zeileis** [comment]
Unfortunately, I agree. I also couldn't find any public repository for the package. The only thing one could try is to write an e-mail to the author and hope for a response. But retiring the package from the task view would also be ok, I think.

**Comment by janetw** [comment]
Fixed: https://github.com/cran-task-views/Agriculture/pull/55
