### ISSUE TITLE
Package 'BMTME' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Agriculture#59]
Package [BMTME](https://CRAN.R-project.org/package=BMTME) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by adamhsparks** [comment]
I've created a pull request to fix the NOTE, https://github.com/frahik/BMTME/pull/14.

Though I note that there is another PR that's been open for a few months and there doesn't appear to be any activity for a few years in the repo, so it may be unmaintained.

**Comment by jpiaskowski** [comment]
I think we should remove this since it doesn't appear to be actively maintained. I've opened a [discussion](https://github.com/cran-task-views/Agriculture/discussions/62) where we can list packages like this that might eventually make their back to CRAN or at least active maintenance.

**Comment by jpiaskowski** [comment]
[package removed](https://github.com/cran-task-views/Agriculture/commit/eea71df595ffb3ecf3b47c98732ab85673bda8a6)
