### ISSUE TITLE
Package 'febr' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Agriculture#61]
Package [febr](https://CRAN.R-project.org/package=febr) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by jpiaskowski** [comment]
Thank you. We have [reached out](https://github.com/Laboratorio-de-Pedometria/febr-package/issues/10).

**Comment by jpiaskowski** [comment]
I recommend removing this package for now since it may be a year or so until it's back on CRAN (according to the package authors).

**Comment by zeileis** [comment]
I agree, that it's time to remove the package as there still isn't any update.

**Comment by jpiaskowski** [comment]
[removed](https://github.com/cran-task-views/Agriculture/commit/69e205a251e2eaff84ceec9b22ef8a5b632a313a)
