### ISSUE TITLE
Consider adding geodata package

### ISSUE THREAD

**Issue by kauedesousa** [cran-task-views/Agriculture#72]
Is interesting that `geodata` don't belong to any task view. Though its applications go beyond Agriculture, I think it is a nice addition to this task view as it provides climate data, adm shapefiles and SPAM maps. 

https://cran.r-project.org/web/packages/geodata/index.html

**Comment by jpiaskowski** [comment]
This looks good. Do you envision it belonging to the data sources section?

**Comment by kauedesousa** [comment]
Yes. Agricultural datasets

**Comment by jpiaskowski** [comment]
addressed in commit https://github.com/cran-task-views/Agriculture/commit/cf8a79260e4a41ae004f6d9ea27da4e643c9a8f7
