### ISSUE TITLE
Package 'smapr' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/Agriculture#74]
Package [smapr](https://CRAN.R-project.org/package=smapr) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by adamhsparks** [comment]
Thanks, @kurthornik. I've sent an e-mail to the maintainer inquiring about the status.

**Comment by adamhsparks** [comment]
@adriancorrendo, I think it's safe to remove this from our CTV. I've not received any sort of response from the package's author to my e-mail.

**Comment by adriancorrendo** [comment]
Thank you, @adamhsparks! I'll proceed to remove [smapr](https://cran.r-project.org/package=smapr) within the next few days.

**Comment by adriancorrendo** [comment]
Addressed in commit [c49fc6b](https://github.com/cran-task-views/Agriculture/commit/c49fc6b2e17d405e0d90ed7717e9afbcb90e52b1)
