### ISSUE TITLE
FAOSTAT package off CRAN & orphaned

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/Agriculture#77]
Archive this? [github repo](https://github.com/mkao006/FAOSTATpackage)

They have other [API resources](https://github.com/FAOSTAT/faostat?tab=readme-ov-file).

**Comment by adriancorrendo** [comment]
Thanks @jpiaskowski . It looks like very reasonable to archive this repo. I'm just a bit concerned about the lack of maintenance since the [last commit](https://github.com/FAOSTAT/faostat/commits/master/) was 5 years ago.

**Comment by jpiaskowski** [comment]
That makes sense. It was passing CRAN checks until very recently, but it doesn't look like anyone plans to continue this.

**Comment by adriancorrendo** [comment]
I just checked and the FAOSTAT package: 
* had a [CRAN update](https://cran.rstudio.com/web/packages/FAOSTAT/index.html) on 2024-05-02, and 
* moved from [github repo](https://github.com/mkao006/FAOSTATpackage) to [Gitlab](https://gitlab.com/paulrougieux/faostatpackage/)

However:
* I couldn't find the old link of [github repo](https://github.com/mkao006/FAOSTATpackage) quoted on the ctv.
* [API resources](https://github.com/FAOSTAT/faostat?tab=readme-ov-file) had its last commit +5 years ago.

So, I believe no action is needed here.
