### ISSUE TITLE
Add FieldSimR

### ISSUE THREAD

**Issue by adriancorrendo** [cran-task-views/Agriculture#78]
I suggest to add [FieldSimR](https://cran.r-project.org/web/packages/FieldSimR/index.html) as a GxE package.

It looks like a good resource that helps with plant breeding analysis including spatial variation, GxE interactions across multiple environments and traits.

**Comment by adamhsparks** [comment]
Looks like a nice package, I agree it should be part of the CTV.

**Comment by adriancorrendo** [comment]
Done, FieldSimR added to the ctv with [commit 3425e54](https://github.com/cran-task-views/Agriculture/commit/3425e54286017fc3344a2479d508cd1750b827cd)
