### ISSUE TITLE
Adding qrlabelr ?

### ISSUE THREAD

**Issue by adriancorrendo** [cran-task-views/Agriculture#79]
Hi there, @adamhsparks @jpiaskowski . Would you agree on adding this package: 
[qrlabelr](https://cran.r-project.org/web/packages/qrlabelr/index.html) 
[vignette here](https://cran.r-project.org/web/packages/qrlabelr/vignettes/qrlabelr.html)

It looks like something useful, to me at least, but I don't see section of the Ag-CTV where it would fit....
It would be a new section maybe call "Miscellaneous"?

Thoughts?

Thanks,
Adrian

**Comment by jpiaskowski** [comment]
I think this works under "experimental design"

**Comment by adamhsparks** [comment]
Agree

**Comment by adriancorrendo** [comment]
qrlabelr package added with commit [cf15bae](https://github.com/cran-task-views/Agriculture/commit/cf15bae24ffef4a03741e211a999fda1ff0f86fb)
