### ISSUE TITLE
Add blocksdesign?  Nested and Crossed Block Designs for Factorial and Unstructured Treatment Sets

### ISSUE THREAD

**Issue by adamhsparks** [cran-task-views/Agriculture#80]
This one just came to my attention this AM thanks to a collaborator.

https://cran.r-project.org/web/packages/blocksdesign/index.html

**Comment by jpiaskowski** [comment]
yes, this looks great. I see it is already in 2 other task views, but it still fits Ag Science.

**Comment by adriancorrendo** [comment]
Thanks, Adam, Julia.

I'll proceed to add [blockdesign](https://cran.r-project.org/web/packages/blocksdesign/index.html) to the ctv. 
It fits very well for quite common designs in Ag science.

Best,
Adrian

**Comment by adriancorrendo** [comment]
`blocksdesign` has been added to the Ag task view with [commit 7ad91f](https://github.com/cran-task-views/Agriculture/commit/7ad91f04128054df1ddae6c92d49f58f5e11d261)
