### ISSUE TITLE
Package 'pergola' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/Agriculture#81]
Package [pergola](https://CRAN.R-project.org/package=pergola) is currently listed in CRAN Task View [Agriculture](https://CRAN.R-project.org/view=Agriculture) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by jpiaskowski** [comment]
@adriancorrendo do you know the status of this?

**Comment by adriancorrendo** [comment]
Thanks, Julia.

Sorry the delay with this.  I gotta check my notifications settings cause I haven't received notification of this issue until you tagged my name here (and I haven't opened it in a few weeks).

I'll proceed to remove the package from the CTV. I also contacted the authors about a situation by posting an issue [here](https://github.com/cbcrg/pergola/issues/27).

Best,
Adrian

**Comment by adriancorrendo** [comment]
'pergola' has been removed from Ag task view with [commit 7ad91f](https://github.com/cran-task-views/Agriculture/commit/7ad91f04128054df1ddae6c92d49f58f5e11d261)
