### ISSUE TITLE
pedmod archived on CRAN

### ISSUE THREAD

**Issue by adriancorrendo** [cran-task-views/Agriculture#84]
@adamhsparks @jpiaskowski 

I ran a check on the ctv and noticed the package [pedmod](https://cran.r-project.org/package=pedmod), currently listed in CRAN Task View [Agriculture](https://cran.r-project.org/view=Agriculture), has been [archived](https://cran-archive.r-project.org/web/checks/2024/2024-07-02_check_results_pedmod.html) on CRAN on 2024-07-02. If the package does not change its status after 60 days from archival (after 2024-09-02), it will be removed from the task view as it often indicates lack of actively maintenance.

Maintainers have been notified with an [issue here](https://github.com/boennecd/pedmod/issues/5) and asked about their maintenance plans.

Adrian

**Comment by jpiaskowski** [comment]
Thanks for being proactive about this!

**Comment by adriancorrendo** [comment]
No action taken by maintainer after being notified on Aug-04-204 https://github.com/boennecd/pedmod/issues/5
And package has been removed from the Taskview.
 
I'll proceed to close this issue
