### ISSUE TITLE
New package suggestion: ggsoiltexture

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/Agriculture#86]
[ggsoiltexture](https://github.com/Saryace/ggsoiltexture)

For soil texture visualization (would go under the soil science section with other pedalogical packages). It's a github pkg at this time. 

Any objections?

**Comment by adamhsparks** [comment]
Oh, nice. I agree, let's add it.

**Comment by adriancorrendo** [comment]
This package is nice! I agree to add it. I used it several times.
I believe it doesn't make to CRAN because it brings several compatibility issues once you load the library.
Plots are great but I had to restart R every single time after creating a plot with it.

**Comment by jpiaskowski** [comment]
added in [commit](https://github.com/cran-task-views/Agriculture/commit/8f6b12e65d27ba86c9d6eac13454d50eead996cb)
