### ISSUE TITLE
Package 'genesysr' could be added to the Views 

### ISSUE THREAD

**Issue by kauedesousa** [cran-task-views/Agriculture#88]
Maybe the package `genesysr` can be added to the Task View as part of agricultural datasets. 

https://cran.r-project.org/web/packages/genesysr/

What do you think?

**Comment by jpiaskowski** [comment]
looks like a good idea.

**Comment by jpiaskowski** [comment]
added in [commit](https://github.com/cran-task-views/Agriculture/commit/743db5d7fb34d5d81d72c138bf54c3ec4642feee)
